    name: nfe-api
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate --schema=apps/api/prisma/schema.prisma && npx prisma db push --schema=apps/api/prisma/schema.prisma --accept-data-loss && npm run db:seed --workspace=api && npm run build --workspace=api
    startCommand: npm run start --workspace=api
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true

  - type: web
    name: nfe-web
    env: node
    plan: free
    buildCommand: npm install && npm run build --workspace=web
    startCommand: npm run start --workspace=web
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: nfe-api
          envVarKey: RENDER_EXTERNAL_URL
